- hosts: all
  name: fetch join token file
  gather_facts: false
  become: yes
  tasks:
  - name: fetch join token file
    ansible.builtin.fetch:
      src: /home/ubuntu/join-command.sh
      dest: ./join-command.sh
      flat: yes
      validate_checksum: false